---
server:
  port: 8080
  contextPath: /SpringBootTask
---
spring:
  profiles: local, default
datasource:
  taskapp:
    url: jdbc:h2:~/task
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.H2Dialect
---
spring:
  profiles: prod
datasource:
  taskapp:
    url: jdbc:mysql://us-cdbr-iron-east-05.cleardb.net:3306/ad_b04406d85aa60b8
    username: b8c5ec0e5ae996
    password: e28ab6b8
    driverClassName: com.mysql.jdbc.Driver
    defaultSchema:
    maxPoolSize: 2
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.MySQLDialect

